### PR TITLE
Add fortran support

### PR DESCRIPTION
**Pull request by alejandrogallo**

### CODE REVIEW

**Comment by alejandrogallo** [comment]
Hi I don't seem to know how to include gfortran in the travis.yaml file. However the tests pass locally.

**Comment by cielavenir** [comment]
@ryanmjacobs
I'm very interested in this. Actually this utility can be compilation-cache platform. We could also add D or Go support.
Or could we introduce plugin support?

**Comment by alejandrogallo** [comment]
However the project seems to be dead...

**Comment by ryanmjacobs** [comment]
Sorry, I’ve been very busy lately. I’ll get back to you tomorrow

**Pull request merged**
