### PR TITLE
create simple install script

### PR DESCRIPTION
**Pull request by ellzey**
can be used remotely or locally.

### CODE REVIEW

**Comment by ryanmjacobs** [comment]
I don't think there's any reason to add an install script. All you need to do is copy a file; this just replaces 2 lines with 95 lines...

**Comment by ellzey** [comment]
so I can ssh to all my servers and run

```
for i in serverA serverB serverC; do 
curl -s https://raw.githubusercontent.com/ryanmjacobs/c/master/install.sh | INSTALL_PREFIX=~/bin bash /dev/stdin inst ; done
```

That's why.

**Comment by alebcay** [comment]
```
for i in serverA serverB serverC do
ssh $i "curl -s https://raw.githubusercontent.com/ryanmjacobs/c/master/c ~/bin ; done
```
Is this not short enough, or am I missing something?

**Comment by ellzey** [comment]
@alebcay but... it has colors :rainbow: :rainbow: (mind you 16 bit)! And :rainbow: warnings! :warning: :warning:!!!

Also has the ability to be updated __IF__ new things are added.

**Comment by alebcay** [comment]
I get the :rainbow: and :warning: - and that's great - but in terms of updating, couldn't you just reinstall it and effectively update it?

Also, one must consider whether or not :rainbow: and :warning: are worth putting into an install script that is half the length of the entire script itself.

**Comment by ellzey** [comment]
but :rainbow: ... 

Let's put this on the wiki.

**Comment by alebcay** [comment]
:+1:

**Comment by ellzey** [comment]
https://github.com/ryanmjacobs/c/wiki/Installation-Helper I updated the script so it can be run independently, either locally or remote.

**Comment by ryanmjacobs** [comment]
> ```
for i in serverA serverB serverC do
ssh $i "curl -s https://raw.githubusercontent.com/ryanmjacobs/c/master/c ~/bin/c ; done
```
Is this not short enough, or am I missing something?

I think this is the best way to install, apart from cloning the repo and copying the file. Personally, I dislike "install scripts" because I never know exactly what they are doing. A simple download using curl is all you need.

**Comment by ellzey** [comment]
Whoa, so you're down with user-maintained packaging repositories such as AUR, but being able to grab the latest HEAD at any time via an install script is a no-no? But doing a `for i in curl` is A-OK? Pick a side here. 

_How many people blindly add public keys to their dpkg repositories without double checking? How many people download a tagged version of your code without also comparing it against a md5sum on a different server?_

Fact is, most don't. 

Libevent has a insanely low ratio of 20 to 1 downloads to md5 checks, that's scary in itself.

Keybase is a good start. md5sum your releases, sign them using the distributed key, put the md5sum on multiple hosts, and we have a nice distributed method of saying "NOPE!" or "YEP!".

To completely tear out the things I did on the wiki was way too premature.

**Comment by alebcay** [comment]
> To completely tear out the things I did on the wiki was way too premature.

As a bystander, I must agree on this point. The wiki content itself should have undergone further discussion before actions were taken. Documentation is an important part of any project, no matter how big or small.

> Keybase is a good start. md5sum your releases, sign them using the distributed key, put the md5sum on multiple hosts, and we have a nice distributed method of saying "NOPE!" or "YEP!".

The question at this point is not whether signing releases is a good idea or not; rather, is it worth the extra effort for:
- first and foremost, users
- second, other contributors
- lastly, yourself
One must calculate the possibility and the risks of such a scenario even occurring. The ideas you bring up here are certainly worth considering, but they should be implemented into the package manager rather than the software package itself.

**Comment by ryanmjacobs** [comment]
>To completely tear out the things I did on the wiki was way too premature.

Sorry about that. My decision to remove the install script from the wiki was rash. I probably should have waited longer. However, an install script that is more than half the length of the actual script seems out of place. A simple copy is much more fit.

> being able to grab the latest HEAD at any time via an install script is a no-no? But doing a `for i in curl` is A-OK?

I don't understand. Isn't `for i in curl` also grabbing from the latest HEAD?

> md5sum your releases, sign them using the distributed key

Lastly, I don't think that it's worth the hassle to md5sum releases here. Let the package managers handle that.

**Comment by ellzey** [comment]
> The question at this point is not whether signing releases is a good idea or not; rather, is it worth the extra effort for...

Yes. If it was a pet-project or a small library, sure, I'll look the other way. But this is a front-end to a __compiler__.

I was just discussing a huge disaster redhat made in 2001 or so where they compiled an entire distribution using a development version of GCC; thus every-single-binary was subject to __that__ bug.

In reality, all of the verification is pretty much drag and drop, see: https://github.com/ellzey/libevhtp/blob/develop/SIGNED.md generated by https://keybase.io/docs/command_line/code_signing

1. Ryan creates a keybase.io account and puts his key everywhere.
2. Ryan makes a release, and signs it.
3. We all track ryan
4. Our scripts can verify using the SIGNED.md __BEFORE__ installing.

> Personally, I dislike "install scripts" because I never know exactly what they are doing. A simple download using curl is all you need.

That's a personal opinion. The wiki snippets was an alternative to your opinion. 

> A simple copy is much more fit.

This is what boggles me. You are completely down with AUR, and bpkg, but in this ticket push for a "just scp it" ideal. 

So is it a security thing, or are you just confused? I assumed it was security related until I remembered you promote bpkg, and I read the following:

> Lastly, I don't think that it's worth the hassle to md5sum releases here. Let the package managers handle that.

You are the package manager!

**Comment by alebcay** [comment]
> You are the package manager!

The point is, once such a method is implemented on this end, it makes it *more* difficult for other systems to integrate with it. As you mentioned, most package managers don't do distributed signature checks, and  to include it specifically with the project would make very little sense. It sounds big enough to be a project of it's own.

As quoted from "Acceptable Formulae" from the Homebrew project:

> We don’t like install-scripts that download things

> Because that circumvents our hash-checks, makes finding/fixing bugs harder, often breaks patches and disables the caching. Almost always you can add a resource to the formula file to handle the separate download and then the installer script will not attempt to load that stuff on demand. Or there is a command line switch where you can point it to the downloaded archive in order to avoid loading.

---

> But this is a front-end to a compiler.

Fair enough. On another note, this is released under the MIT license, so it's technically okay to enforce  *caveat emptor*.

---

> In reality, all of the verification is pretty much drag and drop, see: https://github.com/ellzey/libevhtp/blob/develop/SIGNED.md generated by https://keybase.io/docs/command_line/code_signing

> Ryan creates a keybase.io account and puts his key everywhere.
Ryan makes a release, and signs it.
We all track ryan
Our scripts can verify using the SIGNED.md BEFORE installing.

Alternatively, @ryanmjacobs doesn't have to be the one to sign the releases (granted, it's less trustworthy than if he were the one to do it, but it's still better than nothing I would suppose).

> This is what boggles me. You are completely down with AUR, and bpkg, but in this ticket push for a "just scp it" ideal.

Many people already have AUR and/or `bpkg` installed. To provide it via these systems is most likely a *convenience* to end users. I can remember `bpkg install ryanmjacobs/c` much more easily than `curl <someRandomGitHubAddress>.sh | bash <someObscureArgs>`. On the contrary, if one can figure out the URL, they can also *intuitively* use a command such as `curl <someRandomGitHubAddress> ~/bin/c` - as long as they know how to use `curl`, then they can get the file themselves. The format/syntax of the `install` script is not exactly standardized. I know I certainly didn't know how to use it when I first stumbled across this PR.

**Comment by ryanmjacobs** [comment]
I pretty much agree with everything that @alebcay has said.

By the way, I sign all of the releases. You can view the GPG signatures with `git show v0.10`, or verify them with `git tag --verify v0.10`. My public key can be found [right here](https://pgp.mit.edu/pks/lookup?op=get&search=0x9334C38DCEED707A).

**Pull request closed without merging**
